database:
  db1:
    backup_dir: data/backups
    max_connections: 10
    max_retries: 3
    path: data/framework.db
    timeout: 30
  db2:
    database: your_database_name
    driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc_url: jdbc:sqlserver://{server}:{port};databaseName={database};encrypt=true;trustServerCertificate=true
    max_connections: 10
    max_retries: 3
    password: your_password
    port: 1433
    server: your_server_name
    timeout: 30
    username: your_username
  db2use: db1
framework:
  environment: development
  log_file: logs/framework.log
  log_level: INFO
  output_dir: output
  temp_dir: temp
  version: 1.0.0
