# Episodic to PSV Converter Configuration

plugins:
  - name: episodic_to_csv_converter.py
    function: run
    params:
      input_path: "/path/to/input/episodes.json"
      output_path: "/path/to/output/episodes.psv"
      header: true
      delimiter: "|"  # Use "|" for PSV format
      file_format: "json"  # Options: "json", "xml", "custom"
      flatten: true  # Flatten hierarchical data
      episode_identifier: "episode_id"  # Field that uniquely identifies episodes
      append_mode: false 